name: Frontend CI

on:
  push:
    branches: develop
  pull_request:
    branches: develop

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: web docker build and push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_FRONTEND }}/jejupower_frontend .
        docker push ${{ secrets.DOCKERHUB_FRONTEND }}/jejupower_frontend
        
